server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true;databaseName=product
    username: sa
    password: MyStrongPassword123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  from: ${EMAIL_FROM}

cache:
  url: "127.0.0.1"
  port: 6379
